[tools]
darklua = "seaofvoices/darklua@0.13.1"
lune = "lune-org/lune@0.8.8"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "kampfkarren/selene@0.27.1"
stylua = "johnnymorganz/stylua@0.20.0"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"